version: '3.8'
name: finance-tracker
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app  # Mount project directory for live code changes
      - /usr/src/app/node_modules  # Prevent overwriting node_modules in the container
    ports:
      - "3000:3000"  # Map the app's port to the host
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db  # Ensure the database container starts first
    command: npm run dev  # Enable hot-reloading with nodemon

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Expose the database port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Named volume for database persistence
